### ISSUE TITLE
raidstat.sudoers not recognized in Debian 10

### ISSUE THREAD

**Issue by slefrancois** [ps78674/zabbix-raidstat#2]
On my Debian 10 system, if I directly copy `raidstat/zabbix/raidstat.sudoers` to `/etc/sudoers.d/raidstat.sudoers`, the file is not recognized by sudo. Zabbix returns a "Cannot parse JSON" error, since it receives the sudo password prompt instead of JSON data.

This can be solved by renaming the file to ` /etc/sudoers.d/raidstat`:
[https://linux.die.net/man/5/sudoers](https://linux.die.net/man/5/sudoers)
> sudo will read each file in /etc/sudoers.d, skipping file names that end in '~' or contain a '.' character to avoid causing problems with package manager or editor temporary/backup files.

**Comment by ps78674** [comment]
Readme.md has been updated (l[ink](https://github.com/ps78674/zabbix-raidstat/commit/be6f8b26bc74fa3d36d1e0a1bc0977ec4bd38f88))
